/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#ebf5ff",
        "on-secondary-fixed-variant": "#1a4d5c",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#e8f2fc",
        "primary-fixed-dim": "#a0cde1",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#9fcee0",
        "outline": "#71787c",
        "tertiary": "#003b26",
        "surface-variant": "#dae4ed",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary": "#003747",
        "surface-tint": "#376476",
        "background": "#f6faff",
        "surface-container-high": "#e0e9f3",
        "on-surface-variant": "#41484b",
        "on-primary-fixed-variant": "#1d4c5d",
        "inverse-surface": "#283139",
        "on-background": "#141d24",
        "outline-variant": "#c1c7cc",
        "error": "#ba1a1a",
        "secondary-fixed": "#baeafd",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001f28",
        "tertiary-fixed-dim": "#88d6af",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#7ac8a1",
        "on-tertiary-fixed": "#002113",
        "tertiary-container": "#005438",
        "on-primary-container": "#92bed2",
        "surface-bright": "#f6faff",
        "inverse-primary": "#a0cde1",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#a4f3ca",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container": "#e6eff9",
        "secondary": "#366474",
        "on-primary-fixed": "#001f29",
        "surface": "#f6faff",
        "on-secondary-container": "#3c6b7b",
        "primary-fixed": "#bce9fe",
        "on-surface": "#141d24",
        "surface-dim": "#d2dbe5",
        "secondary-container": "#baeafd",
        "surface-container-highest": "#dae4ed",
        "primary-container": "#1f4e5f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
